---
- name: Check swap
  sudo: yes
  shell: cat /proc/swaps | wc -l
  when: not docker
  changed_when: false
  register: check_swap_cmd

# Workaround for official virtualbox ubuntu image
- name: Enable swap
  sudo: yes
  shell: "{{ item }}"
  with_items:
    - 'fallocate -l 8000M /swapfile'
    - 'chmod 600 /swapfile'
    - 'mkswap /swapfile'
    - 'swapon /swapfile'
    - 'echo "/swapfile none swap defaults 0 0" >> /etc/fstab'
  when: not docker and check_swap_cmd.stdout == '1'

- name: Disable unattended-upgrade
  sudo: yes
  template: src=20auto-upgrades_off dest=/etc/apt/apt.conf.d/20auto-upgrades
  when: not server.unattended_upgrade

- name: Enable unattended-upgrade
  sudo: yes
  template: src=20auto-upgrades_on dest=/etc/apt/apt.conf.d/20auto-upgrades
  when: server.unattended_upgrade
