---
- name: Install https transport for apt
  become: yes
  apt:
    name: apt-transport-https
    state: latest
  when: varnish.repo.https

- name: Include Varnish repository key
  become: yes
  apt_key:
    url: "{{ varnish.repo.key }}"
    state: present

- name: Include Varnish Repository
  become: yes
  apt_repository:
    repo: "{{ varnish.repo.source }}"
    update_cache: yes
    state: present

- name: Install Varnish
  become: yes
  apt:
    name: "{{ varnish.package_name }}"
    state: latest
  register: varnish_install
