---
- name: Remove Varnish Repository
  become: yes
  apt_repository:
    repo: "{{ varnish.repo.source }}"
    state: absent

- name: Uninstall varnish
  become: yes
  apt:
    name: varnish
    state: absent
