---
- name: Uninstall Doxygen and required packages
  become: yes
  apt:
    name: "doxygen"
    state: absent

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
