---
- name: Uninstall Doxygen and required packages
  become: yes
  apt: pkg={{ item }} state=absent
  with_items:
  - doxygen

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
