---
- stat: path=/etc/php/{{ php.version }}/apache2/php.ini
  register: modphp

- stat: path=/etc/apache2/mods-enabled/php{{ php.version }}.conf
  register: php_mod_enabled

- stat: path=/etc/php/{{ php.version }}/cli/php.ini
  register: phpcli

- include: php-switch-version.yml
  when: php_mod_enabled.stat.exists == False

- include: php-cli.yml
  when: phpcli.stat.exists

- include: mod-php.yml
  when: modphp.stat.exists
