---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/php

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: "Uninstall unwanted php versions and packages"
  become: yes
  shell: "dpkg --get-selections | awk '{ print $1 }' | grep -P '.*php[0-9]\\.[0-9].*' | grep -v '{{ php.version }}' | xargs -n1 apt-get purge -y"

- name: "Install php {{ php.version }}"
  become: yes
  apt:
    name: "php{{ php.version }}"
    state: present

- name: Install PHP Packages
  become: yes
  apt:
    name: "php{{ php.version }}-{{ item }}"
    state: present
  loop: "{{ php.packages }}"
  when: php.packages is defined
  notify:
    - restart apache

- include: configure.yml
- include: pecl.yml
