---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/php

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: "Install php {{ php.version }}"
  become: yes
  apt: pkg="php{{ php.version }}" state=latest

- name: Install PHP Packages
  become: yes
  apt: pkg="php{{ php.version }}-{{ item }}" state=latest
  with_items: "{{ php.packages }}"
  when: php.packages is defined
  notify:
    - restart apache

- include: configure.yml
- include: pecl.yml
