---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/php

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: "Install php {{ php.version }}"
  become: yes
  apt:
    name: "php{{ php.version }}"
    state: present

- name: Install PHP Packages
  become: yes
  apt:
    name: "php{{ php.version }}-{{ item }}"
    state: present
  loop: "{{ php.packages }}"
  when: php.packages is defined
  notify:
    - restart apache

- include: configure.yml
- include: pecl.yml
