- name: Turn currently enabled PHP Version off
  become: yes
  shell: 'a2dismod `ls /etc/apache2/mods-enabled | grep -e "php.*\.conf" | sed "s/.conf//g"`'

- name: Turn on the new PHP version
  become: yes
  shell: "a2enmod php{{ php.version }}"
  notify:
    - restart apache

- name: Switch default CLI version
  become: yes
  alternatives:
    name: php
    path: "/usr/bin/php{{ php.version }}"