---
- name: Install xDebug
  become: yes
  apt:
    name: "php{{ php.version }}-xdebug"
    state: present

- name: Capture outgoing IP address
  shell: route | tail -n 1 | awk -F ' ' '{print $1}' | sed 's/\.0$/\.1/g'
  become: yes
  register: xdebug_ip_address

- name: Place xdebug configuration
  template: src=xdebug.ini dest=/etc/php/{{ php.version }}/mods-available/xdebug.ini
  become: yes
  notify: restart apache
